[build]
    publish = "samples/cd/dist/app"
    edge_functions = "samples/cd/dist/netlify/edge-functions"
    command = "pnpm build-cd"

[[edge_functions]]
    path = "/*"
    function = "skew-protection"
